# User config
author: "Eunu Lee"
tagline: "Eunu Lee Homepage"
description: "Hello I'm Eunu!  
<br> An Interior Designer based in Seoul "
keywords: "Eunu, Interior Design, Portfolio"
email: "eunnnnu@gmail.com"
Instagram: "https://www.instagram.com/eunu_xx"
twitter: "https://twitter.com/"
github: "https://github.com/"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed

#analytics

analytics:
  provider: google
  google:
    tracking_id : G-2GP5LKVRQX
