# User config
author: "Eunu Lee"
tagline: "Eunu Lee Homepage"
description: "Hello!
<br> I'm Eunu, an interior designer based in Seoul.
<br> I'm a prospective graduate student of Interior Architecture Design at Hanyang University.
<br> I'm interested in retail environment design and visual merchandising."
keywords: "Eunu, Interior Design, Portfolio"
email: "eunnnnu@gmail.com"
Linkedin: "https://www.instagram.com/eunu_xx"
Twitter: "https://www.instagram.com/eunu_xx"
Instagram: "https://www.instagram.com/eunu_xx"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed

#analytics

analytics:
  provider: google
  google:
    tracking_id : G
